version: "3.9"

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "8085:8085"
    volumes:
      - .:/app
    env_file: .env
    networks:
      - shared-net

networks:
  shared-net:
    external: true